### ISSUE TITLE
How to add plugin with options

### ISSUE THREAD

**Issue by unlight** [ngryman/gulp-bro#11]
```js
const browserify = require('browserify');
const distillify = require('distillify');
const b = browserify({ entries: ['example/entry.js']});
b.plugin(distillify, {
  outputs: {
    file: write('example/build.vendor.js'),
    pattern: 'node_modules/**',
  },
});
```

Seems that is not possible with gulp-bro
```
g.bro({
   plugin: [distillify]
})
```
And `browserify/index.js`
```
    [].concat(opts.plugin).filter(Boolean).forEach(function (p) {
        self.plugin(p, { basedir: opts.basedir });
    });
```
Only `basedir` option will be passed to plugin if we are using `browserify(options)`

**Comment by ngryman** [comment]
*gulp-bro* forwards options to `browserify` directly: https://github.com/substack/node-browserify#browserifyfiles--opts. If you manage to make your plugin work using `browserify` factory function instead of `browserify.plugin`, it should work with `gulp-bro`.

I'm closing this for now, will re-open if you highlight that this is a bug directly related to `gulp-bro`. Thanks!

**Comment by sntran** [comment]
In case if it's not clear enough for those who stumble into this (I did), here is how you would do such thing:

`opts.plugin = [ [pluginFn, pluginOpts] ]`
